# Dev cofig

services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:14.11
    env_file:
      - ./backend/config/.env.example
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432

  algorithm:
    build:
      context: ./algorithm
    volumes:
      - ./algorithm/algorithm:/app/algorithm
      - ./algorithm/web:/app/web
    environment:
      - PYTHONPATH=/app
    command: flask --app web.app run --host=0.0.0.0

  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile.dev
    env_file:
      - ./backend/config/.env.example
    environment:
      - USE_DOCKER=yes
    command: python3 backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend/
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - algorithm

volumes:
  postgres_data:
  postgres_backup_dev: