FROM public.ecr.aws/docker/library/python:3.12
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app

RUN apt update
RUN apt install -y libxml2-dev libxmlsec1-dev libxmlsec1-openssl postgresql-client libpoppler-cpp-dev

COPY ./backend/requirements/base.txt /app
RUN pip install -r /app/base.txt

COPY ./docker/django/entrypoint.sh /app
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
