# Generated by Django 4.1.2 on 2025-02-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duty',
            name='week',
        ),
        migrations.RemoveField(
            model_name='duty',
            name='weekday',
        ),
    ]
