from .helpers import holidays

WEEKDAY = 80
THURSDAY = 70
FRIDAY = 90
SATURDAY = 110
SUNDAY = 100
HOLIDAY = 300

MODIFIER_DUTY_IMPOSSIBLE = 10000
MODIFIER_TWO_DAYS_APART = 30
MODIFIER_THREE_DAYS_APART = 20
MODIFIER_FOUR_DAYS_APART = 10
MODIFIER_FRI_SUN = -60
MODIFIER_THU_SAT = 30
MODIFIER_MORE_THAN_TWO_WEEKENDS = 100
MODIFIER_LESS_THAN_TWO_WEEKENDS = 50
MODIFIER_DONT_STEAL_SUNDAYS = 100
MODIFIER_THURSDAY_IS_ORDINARY = 10
MODIFIER_SATURDAY_IF_ONE_WEEKEND = -30

MAX_NUMBER_OF_DUTIES_PER_MONTH = 15

HOLIDAYS = holidays()